[profile.default]
libs = ["lib"]
names = true
sizes = false
via_ir = false
optimizer = false
optimizer_runs = 999999 
# can lead to white lines 
# bytecode_hash = "none"
evm_version = "shanghai"
[profile.default.invariant]
runs = 16
depth = 256
fail_on_revert = true

[profile.default.fmt]
wrap_comments = true


[profile.build]
test = "/dev/null"
script = "/dev/null"


[profile.test]
via-ir = false


# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
